### ISSUE TITLE
Plugin Name konfigurierbar

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-aufgaben#21]
Unsere Dozenten haben sich an den Namen "Aufgaben" gewöhnt und finden ihr "altes" Tool nicht unter dem neuen Namen "Reflexionsaufgaben" wieder. Ich habe das lokal im manifest geändert. Für Updates wäre es aber cool, wieder den Master unverändert installieren zu können.

**Comment by tgloeggl** [comment]
Das Plugin ist nun tituliert mit "Aufgaben (Relfexion)"
