### ISSUE TITLE
Fehler beim Freigeben von Lösungen für andere Studierende

### ISSUE THREAD

**Issue by mgieseki** [elan-ev/studip-aufgaben#28]
Beim der Suche nach Studierenden, die Zugriff auf abgegebene Lösungen bekommen sollen, erscheint in der Konsole die Fehlermeldung `500 Call to undefined function studip_utf8decode()` und das Hinzufügen der Studierenden schlägt fehl.

https://github.com/elan-ev/studip-aufgaben/search?q=studip_utf8decode
https://github.com/elan-ev/studip-aufgaben/search?q=studip_utf8encode

**Comment by tgloeggl** [comment]
fixed in cba663ea07cd072d6f3c0374ca6e7016b3b2dcf9
