### ISSUE TITLE
Dialog zur Lizenzauswahl wird sofort wieder geschlossen

### ISSUE THREAD

**Issue by mgieseki** [elan-ev/studip-aufgaben#29]
Beim Upload einer Datei öffnet sich kurz die unten angefügte Dialogbox und wird sofort wieder geschlossen. Eine Lizenzauswahl ist damit nicht möglich. 

![message](https://user-images.githubusercontent.com/3620467/138691895-19cbee5e-bfaf-4041-a3f1-9b6decf6d189.gif)

**Comment by tgloeggl** [comment]
fixed in 0a3486a2e1c4c367f875df788f678a2f527c229c
