### ISSUE TITLE
Method _ does not exist

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-aufgaben#33]
Issue is similar to https://github.com/elan-ev/studip-opencast-plugin/issues/700

Houston, we've got a problem.

    Typ: RuntimeException
    Nachricht: Method _ does not exist
    Code: 0
    Stack trace:
    #$ public/plugins_packages/elan-ev/AufgabenPlugin/classes/Controller.class.php(73)
    #0 public/plugins_packages/elan-ev/AufgabenPlugin/app/models/Helper.php(129): EPP\Controller->__call()
    #1 public/plugins_packages/elan-ev/AufgabenPlugin/app/controllers/index.php(289): EPP\Helper::getSidebarInfos()
    #2 vendor/trails/trails.php(557): IndexController->view_task_action()
    #3 app/controllers/studip_controller.php(119): Trails_Controller->perform()
    #4 vendor/trails/trails.php(154): StudipController->perform()
    #5 vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response()
    #6 public/plugins_packages/elan-ev/AufgabenPlugin/AufgabenPlugin.php(184): Trails_Dispatcher->dispatch()
    #7 public/plugins.php(61): AufgabenPlugin->perform()
    #8 {main}

Might be related to our installation, or might be not. All I can tell is that it's a 5.2 installation with PHP 7.4.3-4ubuntu2.18 / (7.4.33 vanilla) done by a contractor.

[Workaround for us](https://github.com/elan-ev/studip-aufgaben/blob/master/classes/Controller.class.php#L63):

```diff
        $variables = get_object_vars($this);
        if (isset($variables[$method]) && is_callable($variables[$method])) {
            return call_user_func_array($variables[$method], $arguments);
+        } else if (method_exists($this, $method)) {
+            return call_user_func_array([$this, $method], $arguments);
        }
        throw new \RuntimeException("Method {$method} does not exist");
    }
```

**Comment by tgloeggl** [comment]
Ist seit einiger Zeit behoben.
