### ISSUE TITLE
Beim Aufruf durch Studierende wird nur ein Fehler angezeigt

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-aufgaben#35]
In 5.3 können Studierende den Reiter nicht aufrufen, wenn eine Aufgabe läuft, folgender Fehler wird angezeigt:
![grafik](https://github.com/elan-ev/studip-aufgaben/assets/6900803/8ce40a01-2c3d-44b5-9d72-c577fe40b698)

Der Link zur Aufgabe funktioniert nicht.

Bei nicht laufenden Aufgaben wird die Liste der beendeten Aufgaben angezeigt, aber sie sind nicht aufrufbar.

Der Dateibereich ist dann auch nicht mehr aufrufbar, auch für Dozierende nicht:
![grafik](https://github.com/elan-ev/studip-aufgaben/assets/6900803/4d446ceb-8615-4912-9034-26a928d36b13)

**Comment by dennis531** [comment]
Ich schaue es mir an.
